module BlackhawkApi
  module Enums
    VALID_ACCOUNT_TYPES = [:CREDIT_CARD, :GIFT_CARD, :LOYALTY_CARD, :PHONE_CARD].freeze
    SUPPORTED_ACCOUNT_TYPES = [:GIFT_CARD].freeze
    ACCOUNT_TRANSACTION_TYPES = [
      :ACCOUNT_ACTIVATION, :ACCOUNT_RELOAD, :ACCOUNT_REDEMPTION,
      :ACCOUNT_FUNDS_TRANSFER, :PAYMENT_AUTHORIZATION, :PAYMENT_AUTHORIZATION_CAPTURE,
      :PAYMENT_CAPTURE, :PAYMENT_REFUND, :PAYMENT_CANCEL, :DIGITAL_ACCOUNT_REQUEST,
      :ACCOUNT_INQUIRY, :SHIPMENT, :RELOAD_IT].freeze
    ACCOUNT_TRANSACTION_STATUS = [:APPROVED, :DECLINED, :ERROR, :MANUAL_REVIEW].freeze
    PAYMENT_PROCESSORS = [:CYBERSOURCE, :ELAVON].freeze
    PAYMENT_NETWORK_TYPES = [:VISA, :MASTERCARD, :DISCOVER, :AMEX, :JCB, :DINERS].freeze
    MESSAGE_REASON_CODES = [
      :PHONE_TOP_UP, :PURCHASE_DIGITAL_ACCOUNT, :BILL_PAYMENT_IMMEDIATE_DELIVERY,
      :BILL_PAYMENT_REGULAR_MAIL_DELIVERY, :BILL_PAYMENT_EXPEDITED_MAIL_DELIVERY,
      :MERCHANDISE_RETURN].freeze
  end
end
