require 'blackhawk_api/client/responses/products/product_catalogs_response'
require 'blackhawk_api/client/responses/products/product_catalog_details_response'
require 'blackhawk_api/client/responses/products/product_catalog_version_response'